/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Book;
import Modele.Client;
import Remote.Controller;
import Remote.HibernateUtil;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author <milly g@VNGTechnology>
 */
public final class Check extends javax.swing.JInternalFrame {

    /**
     * Creates new form Check
     */
    public Check() {
        initComponents();
        popCliCombo();
        popBookCombo();
    }
    DefaultComboBoxModel dc=null;
    DefaultComboBoxModel db=null;
public void popCliCombo(){
List<String> ls=new ArrayList<>();
ls.add("id");
ls.add("name");
dc=(DefaultComboBoxModel) ClientCombo.getModel();
dc.removeAllElements();
    for (String l : ls) {
       dc.addElement(l);
    }

}
public void popBookCombo(){
List<String> ls=new ArrayList<>();
ls.add("category");
ls.add("date");
db= (DefaultComboBoxModel) BookCombo.getModel();
db.removeAllElements();
    for (String l : ls) {
       db.addElement(l);
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cliname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();
        SearchBook = new javax.swing.JLabel();
        BookTxt = new javax.swing.JTextField();
        Author = new javax.swing.JLabel();
        Bname = new javax.swing.JLabel();
        ReturnDate = new javax.swing.JLabel();
        SearchClient = new javax.swing.JButton();
        seaBook = new javax.swing.JButton();
        BookCombo = new javax.swing.JComboBox<>();
        ClientCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        checkIn = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("SearchClient");

        SearchBook.setText("SearchBook");

        BookTxt.setText("1.math 2.bio");

        Author.setText("Author");

        Bname.setText("bname");

        ReturnDate.setText("returnDate");

        SearchClient.setText("Search");
        SearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClientActionPerformed(evt);
            }
        });

        seaBook.setText("SearchBookBtn");
        seaBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaBookActionPerformed(evt);
            }
        });

        jLabel5.setText("date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Author)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bname)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cliname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchClient)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BookTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bookdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ReturnDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seaBook)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(cliname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ClientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchClient)))
                    .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SearchBook)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bookdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Author)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(BookCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bname)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seaBook)
                    .addComponent(ReturnDate))
                .addGap(22, 22, 22))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bookid", "bookname", "author", "date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        checkIn.setText("CheckIn");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });

        checkout.setText("CheckOut");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        jLabel6.setText("checkINbyDate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkIn)
                        .addGap(18, 18, 18)
                        .addComponent(checkout)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchClientActionPerformed
        // TODO add your handling code here:
//        Client c=new Controller().OneClient(Integer.parseInt(IdTxT.getText()));
Client c;
if(ClientCombo.getSelectedItem().toString().equalsIgnoreCase("id")){
 c=new Controller().OneClient(Integer.parseInt(cliname.getText()));
  cliname.setText(c.getFname());
}else{
c=new Controller().clientByName(cliname.getText());
cliname.setText(String.valueOf(c.getClientid()));
}


//        JFileChooser jc =new JFileChooser();
//        int i = jc.showOpenDialog(this);
//        if (i == JFileChooser.APPROVE_OPTION) {
//            f=jc.getSelectedFile();

        f=c.getPhoto();
            BufferedImage img = null;
            try {
               img = ImageIO.read(f);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "shit");
            }

            Image dimg = img.getScaledInstance(Photo.getWidth(), Photo.getHeight(), Image.SCALE_AREA_AVERAGING);
              //Image dimg= img.
            ImageIcon ic = new ImageIcon(dimg);
            Photo.setIcon(ic);
//        }
    }//GEN-LAST:event_SearchClientActionPerformed
    DefaultTableModel dm=null;
    private void seaBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaBookActionPerformed
        // TODO add your handling code here:
        int i;
        Date datee=null;
        String dateee;
        dm=(DefaultTableModel) jTable1.getModel();
        dm.setRowCount(0);
        if(BookCombo.getSelectedItem().toString().equalsIgnoreCase("category")){
//        List<Book> ls=new Controller().bookByCat(BookTxt.getText());
if(BookTxt.getText().equalsIgnoreCase(String.valueOf(1))){
i=1;
}else{
i=0;
}

List<Book> ls=new Controller().findBc(String.valueOf(i));
            for (Iterator<Book> iterator = ls.iterator(); iterator.hasNext();) {
                Book next = iterator.next();
                dm.addRow(new Object[]{
                next.getBookid(),next.getTitle(),next.getAuthor(),
                    next.getDateOfPublication()
                });
                
            }
        }else{
            
            datee=new Date(bookdate.getDate().getTime());
            dateee=datee.toString();
            List<Book> ls=new Controller().bookByDate(dateee);
            for (Iterator<Book> iterator = ls.iterator(); iterator.hasNext();) {
                Book next = iterator.next();
                dm.addRow(new Object[]{
                next.getBookid(),next.getTitle(),next.getAuthor(),
                    next.getDateOfPublication()
                });
            }
        }  
    }//GEN-LAST:event_seaBookActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        // TODO add your handling code here:
        Date datee=new Date(bookdate.getDate().getTime());
        String dateee=datee.toString();
        List<Book> bk=new Controller().bookByDate(dateee);
        dmm=(DefaultTableModel) jTable1.getModel();
        dmm.setRowCount(0);
        for (Iterator<Book> iterator = bk.iterator(); iterator.hasNext();) {
            Book next = iterator.next();
            dmm.addRow(new Object[]{
            next.getBookid(),next.getBc(),
                next.getAuthor(),next.getDateOfPublication()
            });
        }
        
//        dm=(DefaultTableModel) jTable1.getModel();
//     List<Object[]> dmobj=
        
    }//GEN-LAST:event_checkInActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        Client b=new Controller().OneClient(Integer.parseInt(cliname.getText()));
        Date date=Date.valueOf(LocalDate.now());
        String datee=date.toString();
        b.setDateop(datee);
        b.setBks(bs);
        for (Book b1 : bs) {
            b1.setClient(b);
            new Controller().updateBook(b1);
        }
//        new Controller().updateBooks(bs,b.getClientid());
        new Controller().updateClient(b);
    }//GEN-LAST:event_checkoutActionPerformed
DefaultTableModel dmm=null;
List<Book> bs=new ArrayList<>();
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        dmm=(DefaultTableModel) jTable1.getModel();
        int row=jTable1.getSelectedRow();  
        Book b=new Controller().getBook(Integer.parseInt(dmm.getValueAt(row, 0).toString()));
        
        System.out.println(""+b.getBookid());
        
        bs.add(b);
        
        
    }//GEN-LAST:event_jTable1MouseClicked
File f=null;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Bname;
    private javax.swing.JComboBox<String> BookCombo;
    private javax.swing.JTextField BookTxt;
    private javax.swing.JComboBox<String> ClientCombo;
    private javax.swing.JLabel Photo;
    private javax.swing.JLabel ReturnDate;
    private javax.swing.JLabel SearchBook;
    private javax.swing.JButton SearchClient;
    private com.toedter.calendar.JDateChooser bookdate;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkout;
    private javax.swing.JTextField cliname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton seaBook;
    // End of variables declaration//GEN-END:variables

//        public static void main(String[] args) {
//        Check in =new Check();
//        in.setVisible(true);
//    }

}
