/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;


import Modele.Registration;
import Remote.Controller;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author milly g

*/
public class Registrationvue extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register
     */
    public Registrationvue() {
        initComponents();
    }
    
   
   public static String hash(String input,byte [] salt){
       
   StringBuilder hashing = new StringBuilder();
        
       try {
           MessageDigest sha = MessageDigest.getInstance("SHA-1");
           byte[] hashedbytes = sha.digest(input.getBytes());
           sha.update(salt);
          // char[]digits = {'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'};
           for(int i=0; i<hashedbytes.length;i++){
               byte b = hashedbytes[i];
               hashing.append(Integer.toString((hashedbytes[i] & 0xff) +0x100, 16).substring(1));
               
           }
       } catch (NoSuchAlgorithmException e) {
         e.printStackTrace();
       }
    return  hashing.toString();
   
   }
     public static byte[] createsalt() throws NoSuchAlgorithmException {
       SecureRandom se = SecureRandom.getInstance("SHA1PRNG");
       byte[] salt = new byte[16];
       se.nextBytes(salt);
       
       return salt;
    }
     private void clear(){
//     firstname.setText("");
//     lastname.setText("");
     usernames.setText("");
     passwords.setText("");
//     repasswords.setText("");
//     addresses.setText("");
     }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registration = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        usernames = new javax.swing.JTextField();
        passwords = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registration form");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        registration.setBackground(new java.awt.Color(0, 255, 0));
        registration.setForeground(new java.awt.Color(0, 0, 0));
        registration.setText("Register");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(registration, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwords, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernames, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernames, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwords, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registration, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        try {
            // TODO add your handling code here:
            byte [] salted = createsalt();
            String pahash =  hash(passwords.getText(),salted);
//            String repahash = hash(repasswords.getText(),salted);
            
            Registration re = new Registration(usernames.getText(),pahash,salted);
            
            if (usernames.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Add a username");
            }
            else if (passwords.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Add a password");
            }
            
            else{
                new Controller().insertregister(re);
            
    }//GEN-LAST:event_registrationActionPerformed
    clear();
    }   catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Registrationvue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwords;
    private javax.swing.JButton registration;
    private javax.swing.JTextField usernames;
    // End of variables declaration//GEN-END:variables
}
