/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_view;

import Controller.Export;
import Controller.HibernateTest;
import Model.Book;
import Model.Client_M;
import Model.OperationModel;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author <milly g@VNGTechnology>
 */
public class op extends javax.swing.JInternalFrame {

    /**
     * Creates new form op
     */
    public op() {
        
        initComponents();
        populateBookCombo1();
        populateClientCombo1();
        populateTableCheckIn();
//        populateTableCheckOut();
    }
public void populateTableCheckIn(){
    dm= (DefaultTableModel) checkInTable.getModel();
    List<OperationModel> lo= new HibernateTest().getAllOps();
    Object[] arr=lo.toArray();
    for (int i = 0; i < arr.length; i++) {
        dm.addRow(arr);
    }
    

}
public void populateTableCheckOut(){
    dm2= (DefaultTableModel) checkOutTable.getModel();
    List<OperationModel> lo= new HibernateTest().getAllOps();
    lo.forEach(l->{
    dm2.addRow(new Object[]{
        l.getClientname()
    });
    
    });
    for (int i = 0; i < lo.size(); i++) {
      dm2.insertRow(i,new Object[]{
        lo.get(i).getClientname()

    });
    
        for (int j = i,k=0; j < lo.get(i).getBookname().size(); j++) {
            dm2.addRow(new Object[]{
            lo.get(i).getBookname().get(k)
            });
    }

}
}
DefaultTableModel dm=null;
DefaultTableModel dm2=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Check_In_Form = new javax.swing.JPanel();
        clientcombo1 = new javax.swing.JComboBox<>();
        bookcombo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkInTable = new javax.swing.JTable();
        checkInBtn = new javax.swing.JButton();
        pdfCheckIn = new javax.swing.JButton();
        xlsxCheckIn = new javax.swing.JButton();
        searchByCidIn = new javax.swing.JButton();
        searchByCnameIn = new javax.swing.JButton();
        CnameIn = new javax.swing.JTextField();
        CidIn = new javax.swing.JTextField();
        searchByDateIn = new javax.swing.JButton();
        BDateIn = new javax.swing.JTextField();
        BcatIn = new javax.swing.JTextField();
        searchByCatIn = new javax.swing.JButton();
        searchByBookNameIn = new javax.swing.JButton();
        BnameIn = new javax.swing.JTextField();
        searchClientIn = new javax.swing.JComboBox<>();
        searchBookIn = new javax.swing.JComboBox<>();
        CHECK_OUT_form = new javax.swing.JPanel();
        clientcombo2 = new javax.swing.JComboBox<>();
        bookcombo2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkOutTable = new javax.swing.JTable();
        checkOutBtn = new javax.swing.JButton();
        pdfCheckOut = new javax.swing.JButton();
        xlsxCheckOut = new javax.swing.JButton();
        Cid = new javax.swing.JTextField();
        Cname = new javax.swing.JTextField();
        BDate = new javax.swing.JTextField();
        BnameOut = new javax.swing.JTextField();
        BcatOut = new javax.swing.JTextField();
        searchByCnameOut = new javax.swing.JButton();
        searchByCidOut = new javax.swing.JButton();
        searchByBookName = new javax.swing.JButton();
        searchByCat = new javax.swing.JButton();
        searchByDate = new javax.swing.JButton();
        searchBookOut = new javax.swing.JComboBox<>();
        searchClientOut = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        Check_In_Form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check_In_FormMouseClicked(evt);
            }
        });

        clientcombo1.setBackground(new java.awt.Color(204, 0, 255));

        bookcombo1.setBackground(new java.awt.Color(204, 0, 255));
        bookcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookcombo1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Client");

        jLabel2.setText("Book");

        checkInTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "Book", "Status"
            }
        ));
        jScrollPane1.setViewportView(checkInTable);

        checkInBtn.setBackground(new java.awt.Color(204, 0, 204));
        checkInBtn.setText("CHECK_IN");
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });

        pdfCheckIn.setText("Export PDF");
        pdfCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfCheckInActionPerformed(evt);
            }
        });

        xlsxCheckIn.setText("Export xlsx");
        xlsxCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlsxCheckInActionPerformed(evt);
            }
        });

        searchByCidIn.setText("search by C id");
        searchByCidIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCidInActionPerformed(evt);
            }
        });

        searchByCnameIn.setText("search by C name");
        searchByCnameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCnameInActionPerformed(evt);
            }
        });

        CnameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnameInActionPerformed(evt);
            }
        });

        CidIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidInActionPerformed(evt);
            }
        });

        searchByDateIn.setText("search by date");
        searchByDateIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDateInActionPerformed(evt);
            }
        });

        BDateIn.setText("dd-mm-yyyy");

        searchByCatIn.setText("search by category");
        searchByCatIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCatInActionPerformed(evt);
            }
        });

        searchByBookNameIn.setText("search by book Name");
        searchByBookNameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByBookNameInActionPerformed(evt);
            }
        });

        searchClientIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        searchBookIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout Check_In_FormLayout = new javax.swing.GroupLayout(Check_In_Form);
        Check_In_Form.setLayout(Check_In_FormLayout);
        Check_In_FormLayout.setHorizontalGroup(
            Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_In_FormLayout.createSequentialGroup()
                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                        .addComponent(bookcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchClientIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Check_In_FormLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addGap(53, 53, 53)
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByCnameIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchByCidIn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CidIn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CnameIn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchByDateIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchByBookNameIn)
                    .addComponent(searchByCatIn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BcatIn)
                    .addComponent(BnameIn)
                    .addComponent(BDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(Check_In_FormLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(xlsxCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(pdfCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check_In_FormLayout.createSequentialGroup()
                    .addContainerGap(690, Short.MAX_VALUE)
                    .addComponent(searchBookIn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );
        Check_In_FormLayout.setVerticalGroup(
            Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check_In_FormLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BnameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByBookNameIn))
                        .addGap(18, 18, 18)
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BcatIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByCatIn))
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchByDateIn))
                        .addGap(138, 138, 138)
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xlsxCheckIn)
                            .addComponent(pdfCheckIn))
                        .addGap(27, 27, 27)
                        .addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Check_In_FormLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bookcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Check_In_FormLayout.createSequentialGroup()
                                .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CnameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchByCnameIn))
                                    .addGroup(Check_In_FormLayout.createSequentialGroup()
                                        .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CidIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchByCidIn))
                                        .addGap(52, 52, 52)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchClientIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(Check_In_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Check_In_FormLayout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(searchBookIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CHECK_IN", Check_In_Form);

        CHECK_OUT_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHECK_OUT_formMouseClicked(evt);
            }
        });

        clientcombo2.setBackground(new java.awt.Color(204, 0, 255));
        clientcombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientcombo2ActionPerformed(evt);
            }
        });

        bookcombo2.setBackground(new java.awt.Color(204, 0, 255));

        jLabel3.setText("Book");

        jLabel4.setText("Client");

        checkOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "Book", "Status"
            }
        ));
        jScrollPane2.setViewportView(checkOutTable);

        checkOutBtn.setBackground(new java.awt.Color(204, 0, 255));
        checkOutBtn.setText("CHECK_OUT");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        pdfCheckOut.setText("Export PDF");

        xlsxCheckOut.setText("Export xlsx");
        xlsxCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlsxCheckOutActionPerformed(evt);
            }
        });

        Cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidActionPerformed(evt);
            }
        });

        Cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnameActionPerformed(evt);
            }
        });

        BDate.setText("dd-mm-yyyy");

        searchByCnameOut.setText("search by C name");
        searchByCnameOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCnameOutActionPerformed(evt);
            }
        });

        searchByCidOut.setText("search by C id");
        searchByCidOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCidOutActionPerformed(evt);
            }
        });

        searchByBookName.setText("search by book Name");
        searchByBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByBookNameActionPerformed(evt);
            }
        });

        searchByCat.setText("search by category");
        searchByCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCatActionPerformed(evt);
            }
        });

        searchByDate.setText("search by date");
        searchByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByDateActionPerformed(evt);
            }
        });

        searchBookOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        searchClientOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout CHECK_OUT_formLayout = new javax.swing.GroupLayout(CHECK_OUT_form);
        CHECK_OUT_form.setLayout(CHECK_OUT_formLayout);
        CHECK_OUT_formLayout.setHorizontalGroup(
            CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CHECK_OUT_formLayout.createSequentialGroup()
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))
                        .addGap(7, 7, 7)
                        .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchByCnameOut, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(searchByCidOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cid, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addComponent(checkOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchByDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchByBookName)
                                    .addComponent(searchByCat, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BcatOut, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(BnameOut)
                                    .addComponent(BDate)))
                            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xlsxCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                                        .addComponent(pdfCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(searchBookOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(searchClientOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CHECK_OUT_formLayout.setVerticalGroup(
            CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchByCnameOut))
                            .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BnameOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchByCidOut)
                                    .addComponent(searchByBookName))
                                .addGap(18, 18, 18)
                                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BcatOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchByCat))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchByDate)))
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchClientOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pdfCheckOut)
                        .addGap(19, 19, 19))
                    .addGroup(CHECK_OUT_formLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(searchBookOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(CHECK_OUT_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CHECK_OUT_formLayout.createSequentialGroup()
                        .addComponent(xlsxCheckOut)
                        .addGap(18, 18, 18)
                        .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("CHECK_OUT", CHECK_OUT_form);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookcombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookcombo1ActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        int [] a=new int[1];
        a[0]=Integer.parseInt(clientcombo1.getSelectedItem().toString());
        new HibernateTest().deleteOp(a, Integer.parseInt(bookcombo1.getSelectedItem().toString()));

    }//GEN-LAST:event_checkInBtnActionPerformed

    private void Check_In_FormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_In_FormMouseClicked

    }//GEN-LAST:event_Check_In_FormMouseClicked

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        //            new HibernateTest().insertOp(Integer.parseInt(clientcombo1.getSelectedItem().toString()), Integer.parseInt(bookcombo1.getSelectedItem().toString()));

    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void CHECK_OUT_formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECK_OUT_formMouseClicked

    }//GEN-LAST:event_CHECK_OUT_formMouseClicked

    private void xlsxCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlsxCheckOutActionPerformed
        // TODO add your handling code here:
        JFileChooser jc= new JFileChooser();
        if(jc.showSaveDialog(xlsxCheckOut)==JFileChooser.APPROVE_OPTION){
            try {
                File file=jc.getSelectedFile();
                new Export().exportTable(checkOutTable, file);
            } catch (IOException ex) {
                Logger.getLogger(op.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_xlsxCheckOutActionPerformed

    private void xlsxCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlsxCheckInActionPerformed
        // TODO add your handling code here:
        JFileChooser jc= new JFileChooser();
        if(jc.showSaveDialog(xlsxCheckOut)==JFileChooser.APPROVE_OPTION){
            try {
                File file=jc.getSelectedFile();
                new Export().exportTable(checkInTable, file);
            } catch (IOException ex) {
                Logger.getLogger(op.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_xlsxCheckInActionPerformed

    private void pdfCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdfCheckInActionPerformed

    private void CnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnameActionPerformed

    private void CidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidActionPerformed

    private void searchByCnameOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCnameOutActionPerformed
        // TODO add your handling code here:
        searC= (DefaultComboBoxModel) searchClientOut.getModel();
        searC.removeAllElements();
        Client_M lscli=new HibernateTest().searchByName(Cname.getText());
        searC.addElement(lscli.getId());       
    }//GEN-LAST:event_searchByCnameOutActionPerformed
    DefaultComboBoxModel searC=null;
    DefaultComboBoxModel searB=null;
    DefaultComboBoxModel searCIn=null;
    DefaultComboBoxModel searBIn=null;
    private void searchByCidOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCidOutActionPerformed
        // TODO add your handling code here:
        searC=(DefaultComboBoxModel) searchClientOut.getModel();
       Client_M m= new HibernateTest().searchById(Integer.parseInt(Cid.getText()));
       searC.removeAllElements();
       searC.addElement(m.getId());
    }//GEN-LAST:event_searchByCidOutActionPerformed

    private void searchByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDateActionPerformed
        // TODO add your handling code here:
        String datee= BDate.getText();
        searB= (DefaultComboBoxModel) searchBookOut.getModel();      
        List<Book> b=new HibernateTest().searchByBookDate(datee);
        searB.removeAllElements();
        b.forEach(book->{
        searB.addElement(book.getBookNum());
        });
        
    }//GEN-LAST:event_searchByDateActionPerformed

    private void clientcombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientcombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientcombo2ActionPerformed

    private void searchByCidInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCidInActionPerformed
        // TODO add your handling code here:
         searCIn=(DefaultComboBoxModel) searchClientIn.getModel();
       Client_M m= new HibernateTest().searchById(Integer.parseInt(CidIn.getText()));
       searCIn.removeAllElements();
       searCIn.addElement(m.getId());
    }//GEN-LAST:event_searchByCidInActionPerformed

    private void searchByCnameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCnameInActionPerformed
        // TODO add your handling code here:
        searCIn=(DefaultComboBoxModel) searchClientIn.getModel();
       Client_M m= new HibernateTest().searchByName(CnameIn.getText());
       searCIn.removeAllElements();
       searCIn.addElement(m.getId());
    }//GEN-LAST:event_searchByCnameInActionPerformed

    private void CnameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnameInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnameInActionPerformed

    private void CidInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidInActionPerformed

    private void searchByDateInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByDateInActionPerformed
        // TODO add your handling code here:
        
        searBIn= (DefaultComboBoxModel) searchBookIn.getModel();      
        List<Book> b=new HibernateTest().searchByBookDate(BDateIn.getText());
        searBIn.removeAllElements();
        b.forEach(book->{
        searBIn.addElement(book.getBookNum());
        });
        
    }//GEN-LAST:event_searchByDateInActionPerformed

    private void searchByBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByBookNameActionPerformed
        // TODO add your handling code here:
        searB= (DefaultComboBoxModel) searchBookOut.getModel();      
        List<Book> b=new HibernateTest().searchByBookName(BnameOut.getText());
        searB.removeAllElements();
        b.forEach(book->{
        searB.addElement(book.getBookNum());
        });
        
    }//GEN-LAST:event_searchByBookNameActionPerformed

    private void searchByCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCatActionPerformed
        // TODO add your handling code here:
        searB= (DefaultComboBoxModel) searchBookOut.getModel();      
        List<Book> b=new HibernateTest().searchByBookCat(Integer.parseInt(BcatOut.getText()));
        searB.removeAllElements();
        b.forEach(book->{
        searB.addElement(book.getBookNum());
        });
        
    }//GEN-LAST:event_searchByCatActionPerformed

    private void searchByBookNameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByBookNameInActionPerformed
        // TODO add your handling code here:
       searBIn= (DefaultComboBoxModel) searchBookIn.getModel();      
        List<Book> b=new HibernateTest().searchByBookName(BnameIn.getText());
        searBIn.removeAllElements();
        b.forEach(book->{
        searBIn.addElement(book.getBookNum()); 
        });
        
    }//GEN-LAST:event_searchByBookNameInActionPerformed

    private void searchByCatInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCatInActionPerformed
        // TODO add your handling code here:
        searBIn= (DefaultComboBoxModel) searchBookIn.getModel();      
         List<Book> b=new HibernateTest().searchByBookCat(Integer.parseInt(BcatIn.getText()));
        searBIn.removeAllElements();
        b.forEach(book->{
        searBIn.addElement(book.getBookNum());
        
        });
        
    }//GEN-LAST:event_searchByCatInActionPerformed
public void populateClientCombo1(){
    dmc1=(DefaultComboBoxModel) clientcombo1.getModel();
    dmc1.removeAllElements();
    List<Client_M>lscli=new HibernateTest().AllClient();
    lscli.forEach(Client->{
    dmc1.addElement(Client.getId());
});

}
public void populateBookCombo1(){
    dmb1=(DefaultComboBoxModel) bookcombo1.getModel();
List<Book>lsboo=new HibernateTest().AllBooks();
lsboo.forEach(Book->{
dmb1.addElement(Book.getBookNum());
});

}
public void populateClientCombo2(){
    dmc2=(DefaultComboBoxModel) clientcombo2.getModel();
    dmc2.removeAllElements();
List<Client_M>lscli=new HibernateTest().AllClient();
lscli.forEach(Client->{
dmc2.addElement(Client.getId());
});

}
public void populateBookCombo2(){
    dmb2=(DefaultComboBoxModel) bookcombo2.getModel();
List<Book>lsboo=new HibernateTest().AllBooks();
lsboo.forEach(Book->{
dmb2.addElement(Book.getBookNum());
});

}
    DefaultComboBoxModel dmb1=null;
    DefaultComboBoxModel dmc1= null;
    DefaultComboBoxModel dmb2=null;
    DefaultComboBoxModel dmc2= null;
int RowCount=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BDate;
    private javax.swing.JTextField BDateIn;
    private javax.swing.JTextField BcatIn;
    private javax.swing.JTextField BcatOut;
    private javax.swing.JTextField BnameIn;
    private javax.swing.JTextField BnameOut;
    private javax.swing.JPanel CHECK_OUT_form;
    private javax.swing.JPanel Check_In_Form;
    private javax.swing.JTextField Cid;
    private javax.swing.JTextField CidIn;
    private javax.swing.JTextField Cname;
    private javax.swing.JTextField CnameIn;
    private javax.swing.JComboBox<String> bookcombo1;
    private javax.swing.JComboBox<String> bookcombo2;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JTable checkInTable;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JTable checkOutTable;
    private javax.swing.JComboBox<String> clientcombo1;
    private javax.swing.JComboBox<String> clientcombo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton pdfCheckIn;
    private javax.swing.JButton pdfCheckOut;
    private javax.swing.JComboBox<String> searchBookIn;
    private javax.swing.JComboBox<String> searchBookOut;
    private javax.swing.JButton searchByBookName;
    private javax.swing.JButton searchByBookNameIn;
    private javax.swing.JButton searchByCat;
    private javax.swing.JButton searchByCatIn;
    private javax.swing.JButton searchByCidIn;
    private javax.swing.JButton searchByCidOut;
    private javax.swing.JButton searchByCnameIn;
    private javax.swing.JButton searchByCnameOut;
    private javax.swing.JButton searchByDate;
    private javax.swing.JButton searchByDateIn;
    private javax.swing.JComboBox<String> searchClientIn;
    private javax.swing.JComboBox<String> searchClientOut;
    private javax.swing.JButton xlsxCheckIn;
    private javax.swing.JButton xlsxCheckOut;
    // End of variables declaration//GEN-END:variables
    
private void searchClientById(){


}
}
